(library
 (name cpu86core)
 (public_name ocaml-dos.cpu86core)
 (wrapped false)
 (modules cpu86))

(library
 (name dosmachine)
 (public_name ocaml-dos.dosmachine)
 (wrapped false)
 (modules dos_machine dos_state dos_bios dos_dos dos_ems dos_ports dos_video dos_render font8x8)
 (libraries cpu86core))
